from pathlib import Path

# Recovery engine v2 build patch: source-of-truth integration for the test APK.
def replace(path, old, new):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f'pattern not found in {path}: {old[:80]}')
    p.write_text(s.replace(old,new,1))

svc='app/src/main/java/com/pylikv/tachowatch/DriverLiveService.kt'
replace(svc,'    private var availabilityWindowMinutes = 0\n\n    override fun onCreate() {','    private var availabilityWindowMinutes = 0\n    private lateinit var recovery: CounterRecoveryEngine\n\n    override fun onCreate() {')
replace(svc,'        restoreState()\n        live = LiveDidDiagnostic(applicationContext, this)','        restoreState()\n        recovery = CounterRecoveryEngine(applicationContext)\n        live = LiveDidDiagnostic(applicationContext, this)')
replace(svc,'    override fun onLiveConnection(isConnected: Boolean, name: String?) {\n        connected = isConnected\n        deviceName = name','    override fun onLiveConnection(isConnected: Boolean, name: String?) {\n        if (!isConnected && connected && ::recovery.isInitialized) {\n            recovery.recordDisconnect(currentActivity, activityMinutes, continuousMinutes, breakMinutes, shiftDrivingTotal(), workWindowMinutes)\n        }\n        connected = isConnected\n        deviceName = name')
replace(svc,'        if (cycle != null && cycle > lastProcessedCycle) {\n            lastProcessedCycle = cycle\n            processCycle()\n            persistState()\n            evaluateAlerts()\n        }','        if (cycle != null && cycle > lastProcessedCycle) {\n            lastProcessedCycle = cycle\n            processCycle()\n            persistState()\n            recovery.recordLive(currentActivity, activityMinutes, continuousMinutes, breakMinutes, shiftDrivingTotal(), workWindowMinutes)\n            evaluateAlerts()\n        }')
replace(svc,'    private fun processCycle() {\n        val restNow = isRest(currentActivity)\n        val restMinutes = if (restNow) maxOf(activityMinutes, breakMinutes) else 0\n','    private fun processCycle() {\n        val restNow = isRest(currentActivity)\n        val restMinutes = if (restNow) maxOf(activityMinutes, breakMinutes) else 0\n\n        val reconnect = recovery.reconcileFirstLiveAfterReconnect(\n            CounterRecoveryEngine.Point(System.currentTimeMillis(), "LIVE", currentActivity, activityMinutes, continuousMinutes, breakMinutes, shiftDrivingTotal(), workWindowMinutes, true)\n        )\n        if (reconnect?.dailyRestObserved == true) {\n            shiftCompletedMinutes = 0\n            previousContinuousMinutes = continuousMinutes\n            workWindowMinutes = 0\n            otherWorkWindowMinutes = 0\n            availabilityWindowMinutes = 0\n            previousActivity = currentActivity\n            previousActivityDuration = activitySourceMinutes()\n        } else if (reconnect?.qualifyingDrivingBreakObserved == true) {\n            workWindowMinutes = 0\n            previousActivity = currentActivity\n            previousActivityDuration = activitySourceMinutes()\n        }\n')

ui='app/src/main/java/com/pylikv/tachowatch/DriverDashboardActivityV2.kt'
replace(ui,'    private fun restTitle(r:HistoryData.RestInfo):String=when{r.weekly&&r.compensationCreatedMinutes>0->"🛏 СОКРАЩЁННЫЙ НЕДЕЛЬНЫЙ ОТДЫХ  ${HistoryData.fmt(r.actualMinutes)}\\nКомпенсация ${HistoryData.fmt(r.compensationRemainingMinutes)} • до ${r.compensationDueDate?.let(HistoryData::prettyDate)?:"—"}";','    private fun restTitle(r:HistoryData.RestInfo):String=when{r.weekly&&r.compensationCreatedMinutes>0->"🛏 СОКРАЩЁННЫЙ НЕДЕЛЬНЫЙ ОТДЫХ  ${HistoryData.fmt(r.actualMinutes)}\\n"+(if(r.compensationPaidDate!=null) "Компенсация ${HistoryData.fmt(r.compensationCreatedMinutes)} • отдана ${HistoryData.prettyDate(r.compensationPaidDate)}" else "Компенсация ${HistoryData.fmt(r.compensationCreatedMinutes)} • отдать до ${r.compensationDueDate?.let(HistoryData::prettyDate)?:"—"}");')
replace(ui,'        dailyRestTime.text="${HistoryData.fmt(actual.coerceAtMost(11*60))} / 11:00";dailyRestSub.text=when{actual>=11*60->"✓ нормальный суточный отдых 11:00";actual>=9*60->"✓ сокращённый 9:00 • до 11:00 ${HistoryData.fmt(11*60-actual)}";actual>=3*60->"✓ первая часть 3:00 зафиксирована • следующая ступень 9:00";resting->"до фиксации 3:00 осталось ${HistoryData.fmt((3*60-actual).coerceAtLeast(0))}";else->"ступени: 3:00 → 9:00 → 11:00"};val dailyColor=when{actual>=9*60->GREEN;actual>=3*60->YELLOW;else->RED};dailyRestTime.setTextColor(dailyColor);setRestProgress(dailyRestFrame,dailyRestProgress,actual.coerceAtMost(11*60)/(11f*60f),dailyColor)','        val dailyActual=if(resting)maxOf(activityMinutes,breakMinutes) else 0;dailyRestTime.text="${HistoryData.fmt(dailyActual.coerceAtMost(11*60))} / 11:00";dailyRestSub.text=when{dailyActual>=11*60->"✓ нормальный суточный отдых 11:00";dailyActual>=9*60->"✓ сокращённый 9:00 • до 11:00 ${HistoryData.fmt(11*60-dailyActual)}";dailyActual>=3*60->"✓ первая часть 3:00 зафиксирована • следующая ступень 9:00";resting->"до фиксации 3:00 осталось ${HistoryData.fmt((3*60-dailyActual).coerceAtLeast(0))}";else->"ступени: 3:00 → 9:00 → 11:00"};val dailyColor=when{dailyActual>=9*60->GREEN;dailyActual>=3*60->YELLOW;else->RED};dailyRestTime.setTextColor(dailyColor);setRestProgress(dailyRestFrame,dailyRestProgress,dailyActual.coerceAtMost(11*60)/(11f*60f),dailyColor)')
print('recovery-engine-v2 patches applied')
